### ISSUE TITLE
Use GitHub Actions to let contributors open PRs for wiki pages

### ISSUE THREAD

**Issue by jcbhmr** [btzy/nativefiledialog-extended#102]
Something like https://github.com/Andrew-Chen-Wang/github-wiki-action or https://github.com/spenserblack/actions-wiki

```yml
name: Publish wiki
on:
  push:
    branches: [main]
    paths:
      - wiki/**
      - .github/workflows/publish-wiki.yml
concurrency:
  group: publish-wiki
  cancel-in-progress: true
permissions:
  contents: write
jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Andrew-Chen-Wang/github-wiki-action@v4
```

<details><summary>If you really want to, you can also sync in reverse (wiki to repo)</summary>

```yml
name: Pull wiki
on:
  gollum:
  push:
    branches: main
    paths: .github/workflows/pull-wiki.yml
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  pull-wiki:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          export GIT_DIR=$(mktemp -d)
          trap 'rm -rf "$GIT_DIR"' SIGINT SIGTERM ERR EXIT
          export GIT_WORK_TREE=wiki
          git clone https://github.com/jcbhmr/.github.wiki.git "$GIT_DIR" --bare
          git config --unset core.bare
          git reset --hard
      - uses: EndBug/add-and-commit@v9
        with:
          message: '[skip actions] Pull wiki'
```

</details>
